spring:
  application:
    name: my-project
  datasource:
    url: jdbc:postgresql://ep-dawn-snowflake-a1vogasb-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_O7Zzd6XAhiRl
    driver-clas-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
